baseURL = 'https://alexsci.com/blog/'
languageCode = 'en-us'
title = "Robert Alexander's Tech Blog"
permalinks.post = '/:slug/'
canonifyURLs = true

[params]
  [params.author]
    email = 'robert@robalexdev.com'
    name = 'Robert Alexander'

# Legacy RSS feed name
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
